-- ============================================================================
-- UP AND DOWN · GOLF LESSON LEADS · V1
-- Ejecutar una sola vez en Supabase SQL Editor.
-- ============================================================================

begin;

create table if not exists public.golf_lesson_leads (
  id uuid primary key default gen_random_uuid(),
  public_token uuid not null default gen_random_uuid(),

  name text not null,
  phone text not null,
  phone_digits text not null,

  skill_level text not null
    check (skill_level in ('new','beginner','intermediate','advanced','competitive')),

  goal_category text not null
    check (goal_category in ('starting','consistency','distance','irons','short_game','putting','strategy','other')),

  goal_text text,

  consent_contact boolean not null default true
    check (consent_contact = true),
  consent_at timestamptz not null default now(),
  consent_version text not null default 'golf_lessons_contact_v1',
  consent_text text not null,

  language text not null default 'es'
    check (language in ('es','en')),

  source text not null default 'home_classes',
  affiliate_code text,

  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  referrer_host text,

  selected_instructor text
    check (selected_instructor is null or selected_instructor in ('rodrigo-uribe','mario-navarro')),
  selected_at timestamptz,

  status text not null default 'new'
    check (status in ('new','contacted','qualified','scheduled','completed','closed')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists golf_lesson_leads_public_token_key
  on public.golf_lesson_leads(public_token);

create index if not exists golf_lesson_leads_created_at_idx
  on public.golf_lesson_leads(created_at desc);

create index if not exists golf_lesson_leads_skill_level_idx
  on public.golf_lesson_leads(skill_level);

create index if not exists golf_lesson_leads_goal_category_idx
  on public.golf_lesson_leads(goal_category);

create index if not exists golf_lesson_leads_selected_instructor_idx
  on public.golf_lesson_leads(selected_instructor);

create index if not exists golf_lesson_leads_affiliate_code_idx
  on public.golf_lesson_leads(affiliate_code);

create index if not exists golf_lesson_leads_phone_digits_idx
  on public.golf_lesson_leads(phone_digits);


create table if not exists public.golf_lesson_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.golf_lesson_leads(id) on delete cascade,
  event_type text not null
    check (event_type in ('lead_created','instructor_interest')),
  instructor_slug text
    check (instructor_slug is null or instructor_slug in ('rodrigo-uribe','mario-navarro')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists golf_lesson_events_lead_id_idx
  on public.golf_lesson_events(lead_id);

create index if not exists golf_lesson_events_created_at_idx
  on public.golf_lesson_events(created_at desc);

create index if not exists golf_lesson_events_instructor_idx
  on public.golf_lesson_events(instructor_slug);


alter table public.golf_lesson_leads enable row level security;
alter table public.golf_lesson_events enable row level security;


drop policy if exists "Admins can view golf lesson leads" on public.golf_lesson_leads;
create policy "Admins can view golf lesson leads"
on public.golf_lesson_leads
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can update golf lesson leads" on public.golf_lesson_leads;
create policy "Admins can update golf lesson leads"
on public.golf_lesson_leads
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can view golf lesson events" on public.golf_lesson_events;
create policy "Admins can view golf lesson events"
on public.golf_lesson_events
for select
to authenticated
using (public.is_admin());

revoke all on table public.golf_lesson_leads from anon, authenticated;
revoke all on table public.golf_lesson_events from anon, authenticated;

grant select, update on table public.golf_lesson_leads to authenticated;
grant select on table public.golf_lesson_events to authenticated;


create or replace function public.create_golf_lesson_lead(
  p_name text,
  p_phone text,
  p_skill_level text,
  p_goal_category text,
  p_goal_text text default null,
  p_consent boolean default false,
  p_language text default 'es',
  p_affiliate_code text default null,
  p_utm_source text default null,
  p_utm_medium text default null,
  p_utm_campaign text default null,
  p_utm_content text default null,
  p_utm_term text default null,
  p_referrer_host text default null
)
returns table(lead_id uuid, lead_token uuid)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_name text;
  v_phone text;
  v_phone_digits text;
  v_skill text;
  v_goal text;
  v_goal_text text;
  v_language text;
  v_affiliate_code text;
  v_id uuid;
  v_token uuid;
  v_consent_text text :=
    'Autorizo a UP AND DOWN a contactarme por WhatsApp, SMS o llamada para atender mi solicitud de clases y dar seguimiento relacionado con servicios de golf. Mi información será utilizada para gestionar esta solicitud, atención comercial y análisis interno; no será vendida a terceros. Puedo solicitar dejar de recibir mensajes en cualquier momento.';
begin
  v_name := btrim(coalesce(p_name,''));
  v_phone := btrim(coalesce(p_phone,''));
  v_phone_digits := regexp_replace(v_phone,'[^0-9]','','g');
  v_skill := btrim(coalesce(p_skill_level,''));
  v_goal := btrim(coalesce(p_goal_category,''));
  v_goal_text := nullif(left(btrim(coalesce(p_goal_text,'')),1000),'');
  v_language := case when p_language = 'en' then 'en' else 'es' end;

  if p_consent is distinct from true then raise exception 'CONTACT_CONSENT_REQUIRED'; end if;
  if char_length(v_name) < 2 or char_length(v_name) > 120 then raise exception 'INVALID_NAME'; end if;
  if char_length(v_phone_digits) < 10 or char_length(v_phone_digits) > 15 then raise exception 'INVALID_PHONE'; end if;
  if v_skill not in ('new','beginner','intermediate','advanced','competitive') then raise exception 'INVALID_SKILL_LEVEL'; end if;
  if v_goal not in ('starting','consistency','distance','irons','short_game','putting','strategy','other') then raise exception 'INVALID_GOAL'; end if;

  if nullif(btrim(coalesce(p_affiliate_code,'')),'') is not null then
    select s.code into v_affiliate_code
    from public.affiliate_sellers s
    where s.is_active = true
      and s.code = upper(btrim(p_affiliate_code))
    limit 1;
  end if;

  insert into public.golf_lesson_leads(
    name,phone,phone_digits,skill_level,goal_category,goal_text,
    consent_contact,consent_at,consent_version,consent_text,language,
    affiliate_code,utm_source,utm_medium,utm_campaign,utm_content,utm_term,referrer_host
  )
  values(
    v_name,v_phone,v_phone_digits,v_skill,v_goal,v_goal_text,
    true,now(),'golf_lessons_contact_v1',v_consent_text,v_language,
    v_affiliate_code,
    nullif(left(btrim(coalesce(p_utm_source,'')),160),''),
    nullif(left(btrim(coalesce(p_utm_medium,'')),160),''),
    nullif(left(btrim(coalesce(p_utm_campaign,'')),160),''),
    nullif(left(btrim(coalesce(p_utm_content,'')),160),''),
    nullif(left(btrim(coalesce(p_utm_term,'')),160),''),
    nullif(left(btrim(coalesce(p_referrer_host,'')),255),'')
  )
  returning id, public_token into v_id, v_token;

  insert into public.golf_lesson_events(lead_id,event_type,metadata)
  values(
    v_id,'lead_created',
    jsonb_build_object(
      'skill_level',v_skill,
      'goal_category',v_goal,
      'language',v_language,
      'affiliate_code',v_affiliate_code
    )
  );

  return query select v_id,v_token;
end;
$function$;


create or replace function public.record_golf_instructor_interest(
  p_lead_id uuid,
  p_lead_token uuid,
  p_instructor_slug text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_exists boolean;
begin
  if p_instructor_slug not in ('rodrigo-uribe','mario-navarro') then
    raise exception 'INVALID_INSTRUCTOR';
  end if;

  select exists(
    select 1
    from public.golf_lesson_leads l
    where l.id = p_lead_id
      and l.public_token = p_lead_token
  ) into v_exists;

  if not v_exists then raise exception 'INVALID_LEAD_TOKEN'; end if;

  update public.golf_lesson_leads
     set selected_instructor=p_instructor_slug,
         selected_at=now(),
         updated_at=now()
   where id=p_lead_id
     and public_token=p_lead_token;

  insert into public.golf_lesson_events(lead_id,event_type,instructor_slug)
  values(p_lead_id,'instructor_interest',p_instructor_slug);

  return true;
end;
$function$;


revoke execute on function public.create_golf_lesson_lead(
  text,text,text,text,text,boolean,text,text,text,text,text,text,text,text
) from public;

grant execute on function public.create_golf_lesson_lead(
  text,text,text,text,text,boolean,text,text,text,text,text,text,text,text
) to anon, authenticated, service_role;


revoke execute on function public.record_golf_instructor_interest(uuid,uuid,text)
from public;

grant execute on function public.record_golf_instructor_interest(uuid,uuid,text)
to anon, authenticated, service_role;

commit;

notify pgrst, 'reload schema';

select
  'golf_lesson_leads' as object,
  exists(select 1 from information_schema.tables where table_schema='public' and table_name='golf_lesson_leads') as ok
union all
select
  'golf_lesson_events',
  exists(select 1 from information_schema.tables where table_schema='public' and table_name='golf_lesson_events')
union all
select
  'create_golf_lesson_lead anon execute',
  has_function_privilege('anon','public.create_golf_lesson_lead(text,text,text,text,text,boolean,text,text,text,text,text,text,text,text)','EXECUTE')
union all
select
  'record_golf_instructor_interest anon execute',
  has_function_privilege('anon','public.record_golf_instructor_interest(uuid,uuid,text)','EXECUTE');
