"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Row={product_id:string;product_name:string;variant_id:string;variant_title:string;sku:string;barcode:string|null;stock:number;low_stock_threshold:number;is_default:boolean};

export default function InventoryAdmin(){
 const db=useMemo(()=>createClient(),[]); const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState(""); const [tab,setTab]=useState<"stock"|"move"|"variants"|"barcode">("stock"); const [search,setSearch]=useState("");
 const load=async()=>{setLoading(true);const {data,error}=await db.rpc("admin_inventory_catalog");if(error)setMsg(error.message);else setRows((data?.rows||[]) as Row[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=rows.filter(r=>`${r.product_name} ${r.variant_title} ${r.sku} ${r.barcode||""}`.toLowerCase().includes(search.toLowerCase()));
 const products=Array.from(new Map(rows.map(r=>[r.product_id,r.product_name])).entries());
 async function move(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let q=Number(f.get("qty"));const type=String(f.get("type"));if(["damage","supplier_return"].includes(type))q=-q;const {error}=await db.rpc("admin_inventory_adjust",{p_variant_id:String(f.get("variant")),p_quantity_change:q,p_reason:String(f.get("reason")),p_movement_type:type});setMsg(error?error.message:"Movimiento registrado correctamente.");if(!error){e.currentTarget.reset();load()}}
 async function variant(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const attrs:Record<string,string>={};String(f.get("attrs")||"").split(",").forEach(p=>{const [k,...v]=p.split("=");if(k?.trim()&&v.join("=").trim())attrs[k.trim()]=v.join("=").trim()});const {error}=await db.rpc("admin_inventory_save_variant",{p_product_id:String(f.get("product")),p_variant_id:null,p_title:String(f.get("title")),p_sku:String(f.get("sku")),p_barcode:String(f.get("barcode"))||null,p_attributes:attrs,p_price:null,p_sale_price:null,p_low_stock_threshold:2,p_is_active:true});setMsg(error?error.message:"Variante creada. Registra ahora su entrada inicial.");if(!error){e.currentTarget.reset();load()}}
 async function barcode(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const id=String(f.get("variant"));const row=rows.find(r=>r.variant_id===id);if(!row)return;const {error}=await db.rpc("admin_inventory_save_variant",{p_product_id:row.product_id,p_variant_id:id,p_title:row.variant_title,p_sku:row.sku,p_barcode:String(f.get("barcode"))||null,p_attributes:{},p_price:null,p_sale_price:null,p_low_stock_threshold:row.low_stock_threshold??2,p_is_active:true});setMsg(error?error.message:"Código de barras actualizado.");if(!error){e.currentTarget.reset();load()}}
 return <main className="min-h-screen bg-[#F8F6F2] text-[#1E1E1E] p-4 md:p-8"><div className="mx-auto max-w-6xl">
  <div className="flex flex-wrap items-end justify-between gap-4 border-b border-[#143E35]/15 pb-5"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-[#C8A86B]">Up & Down · Administración</div><h1 className="mt-2 text-4xl md:text-6xl font-semibold text-[#143E35]">Inventario</h1><p className="mt-2 text-sm text-[#68736F]">Existencias, movimientos, variantes y códigos de barras.</p></div><Link href="/admin" className="rounded-full border border-[#143E35] px-5 py-3 text-sm font-bold text-[#143E35]">← Panel administrativo</Link></div>
  <div className="my-6 flex gap-2 overflow-auto">{[["stock","Existencias"],["move","Entradas y salidas"],["variants","Variantes"],["barcode","Códigos de barras"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as typeof tab)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab===k?"bg-[#143E35] text-white":"bg-white border border-[#143E35]/15 text-[#143E35]"}`}>{l}</button>)}</div>
  {msg&&<div className="mb-5 rounded-xl bg-white border border-[#143E35]/15 p-4 text-sm">{msg}</div>}
  {tab==="stock"&&<section className="rounded-2xl bg-white border border-[#143E35]/15 overflow-hidden"><div className="p-4 border-b border-[#143E35]/10"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto, talla, SKU o barcode…" className="w-full rounded-xl border border-[#143E35]/15 p-3"/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#F3F6F4] text-left text-xs uppercase text-[#68736F]"><tr><th className="p-3">Producto</th><th className="p-3">Variante</th><th className="p-3">SKU</th><th className="p-3">Barcode</th><th className="p-3 text-right">Stock</th></tr></thead><tbody>{filtered.map(r=><tr key={r.variant_id} className="border-t border-[#143E35]/10"><td className="p-3 font-bold text-[#143E35]">{r.product_name}</td><td className="p-3">{r.variant_title}{r.is_default?" · principal":""}</td><td className="p-3">{r.sku}</td><td className="p-3">{r.barcode||"—"}</td><td className={`p-3 text-right font-bold ${Number(r.stock)<=Number(r.low_stock_threshold)?"text-red-700":"text-[#143E35]"}`}>{r.stock}</td></tr>)}</tbody></table></div>{loading&&<div className="p-6 text-center">Cargando…</div>}</section>}
  {tab==="move"&&<FormBox title="Registrar entrada / salida"><form onSubmit={move} className="grid gap-3"><select name="variant" required className="field"><option value="">Producto / variante…</option>{rows.map(r=><option key={r.variant_id} value={r.variant_id}>{r.product_name} · {r.variant_title} · stock {r.stock}</option>)}</select><div className="grid md:grid-cols-2 gap-3"><select name="type" className="field"><option value="restock">Entrada / recepción</option><option value="adjustment">Ajuste positivo</option><option value="damage">Salida / daño o merma</option><option value="supplier_return">Salida / devolución a proveedor</option></select><input name="qty" type="number" min="1" required placeholder="Piezas" className="field"/></div><input name="reason" minLength={3} required placeholder="Motivo / referencia / factura" className="field"/><button className="btn">Registrar movimiento</button></form></FormBox>}
  {tab==="variants"&&<FormBox title="Crear variante de producto"><form onSubmit={variant} className="grid gap-3"><select name="product" required className="field"><option value="">Producto padre…</option>{products.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select><div className="grid md:grid-cols-2 gap-3"><input name="title" required placeholder="Ej. Blanca · M" className="field"/><input name="sku" required placeholder="SKU único" className="field"/></div><div className="grid md:grid-cols-2 gap-3"><input name="barcode" placeholder="Barcode / UPC" className="field"/><input name="attrs" placeholder="talla=M,color=Blanco" className="field"/></div><p className="text-xs text-[#68736F]">La variante nace con stock 0. Su existencia se agrega desde Entradas y salidas.</p><button className="btn">Crear variante</button></form></FormBox>}
  {tab==="barcode"&&<FormBox title="Asignar o cambiar código de barras"><form onSubmit={barcode} className="grid gap-3"><select name="variant" required className="field"><option value="">Producto / variante…</option>{rows.map(r=><option key={r.variant_id} value={r.variant_id}>{r.product_name} · {r.variant_title} · {r.barcode||"sin barcode"}</option>)}</select><input name="barcode" autoFocus inputMode="numeric" required placeholder="Escanea aquí el código" className="field"/><p className="text-xs text-[#68736F]">Haz clic en el campo y pasa el lector. El código debe ser único.</p><button className="btn">Guardar barcode</button></form></FormBox>}
 </div><style jsx>{`.field{width:100%;border:1px solid rgba(20,62,53,.16);border-radius:12px;padding:12px;background:#fff}.btn{border:0;border-radius:12px;padding:12px 16px;background:#143E35;color:white;font-weight:800}`}</style></main>
}
function FormBox({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl bg-white border border-[#143E35]/15 p-5 md:p-7"><h2 className="mb-5 text-2xl font-semibold text-[#143E35]">{title}</h2>{children}</section>}
