"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Row={product_id:string;product_name:string;variant_id:string;variant_title:string;sku:string;barcode:string|null;stock:number;low_stock_threshold:number;is_default:boolean};
type Movement={id:string;created_at:string;movement_type:string;quantity_change:number;stock_before:number;stock_after:number;note:string|null;product_name:string|null;variant_title:string|null;sku:string|null;barcode:string|null;order_id:string|null;pos_sale_id:string|null};
const movementLabel:Record<string,string>={restock:"Entrada / recepción",adjustment:"Ajuste",damage:"Daño / merma",supplier_return:"Devolución a proveedor",sale:"Venta POS",pos_sale:"Venta POS",return:"Devolución cliente"};

export default function InventoryAdmin(){
 const db=useMemo(()=>createClient(),[]); const [rows,setRows]=useState<Row[]>([]); const [movements,setMovements]=useState<Movement[]>([]); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState(""); const [tab,setTab]=useState<"stock"|"move"|"log">("stock"); const [search,setSearch]=useState("");
 const load=async()=>{setLoading(true);const [{data,error},{data:logData,error:logError}]=await Promise.all([db.rpc("admin_inventory_catalog"),db.rpc("admin_inventory_movement_log",{p_limit:300})]);if(error)setMsg(error.message);else setRows((data?.rows||[]) as Row[]);if(logError)setMsg(logError.message);else setMovements((logData?.rows||[]) as Movement[]);setLoading(false)}; useEffect(()=>{load()},[]);
 const filtered=rows.filter(r=>`${r.product_name} ${r.variant_title} ${r.sku} ${r.barcode||""}`.toLowerCase().includes(search.toLowerCase())); const filteredMovements=movements.filter(m=>`${m.product_name||""} ${m.variant_title||""} ${m.sku||""} ${m.barcode||""} ${m.note||""} ${m.movement_type}`.toLowerCase().includes(search.toLowerCase()));
 const totalUnits=rows.reduce((a,r)=>a+Number(r.stock||0),0), low=rows.filter(r=>Number(r.stock)<=Number(r.low_stock_threshold)).length, available=rows.filter(r=>Number(r.stock)>Number(r.low_stock_threshold)).length;
 async function move(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let q=Number(f.get("qty"));const type=String(f.get("type"));if(["damage","supplier_return"].includes(type))q=-q;const {error}=await db.rpc("admin_inventory_adjust",{p_variant_id:String(f.get("variant")),p_quantity_change:q,p_reason:String(f.get("reason")),p_movement_type:type});setMsg(error?error.message:"Movimiento registrado correctamente.");if(!error){e.currentTarget.reset();load()}}
 return <main className="min-h-screen bg-[#F7F5F1] text-[#1E1E1E] px-4 py-6 md:px-8 md:py-8"><div className="mx-auto max-w-[1280px]">
  <header className="rounded-[28px] border border-[#143E35]/10 bg-white px-5 py-6 shadow-[0_18px_55px_rgba(20,62,53,.07)] md:px-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="text-[10px] font-extrabold uppercase tracking-[.24em] text-[#C8A86B]">Up & Down · Administración</div><h1 className="mt-2 font-serif text-4xl font-semibold leading-none text-[#143E35] md:text-6xl">Inventario</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#68736F]">Consulta existencias, registra entradas o salidas y revisa la trazabilidad de cada SKU desde un solo lugar.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className="rounded-full bg-[#143E35] px-5 py-3 text-xs font-extrabold text-white shadow-sm">Productos</Link><Link href="/admin" className="rounded-full border border-[#143E35]/15 bg-white px-5 py-3 text-xs font-extrabold text-[#143E35]">← Panel administrativo</Link></div></div></header>
  <section className="my-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Unidades disponibles" value={totalUnits} hint="Existencia física total"/><Metric label="SKUs / variantes" value={rows.length} hint="Artículos controlados"/><Metric label="Disponibles" value={available} hint="Sobre stock mínimo"/><Metric label="Requieren atención" value={low} hint="Stock bajo o agotado" warn={low>0}/></section>
  <section className="rounded-[26px] border border-[#143E35]/10 bg-white shadow-[0_18px_55px_rgba(20,62,53,.06)]"><div className="border-b border-[#143E35]/10 p-3 md:flex md:items-center md:justify-between md:gap-4"><div className="flex gap-1 overflow-auto rounded-2xl bg-[#F1F3F1] p-1">{[["stock","Existencias"],["move","Entradas y salidas"],["log","Bitácora"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as typeof tab)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-extrabold transition ${tab===k?"bg-white text-[#143E35] shadow-sm":"text-[#68736F] hover:text-[#143E35]"}`}>{l}</button>)}</div>{(tab==="stock"||tab==="log")&&<div className="mt-3 md:mt-0 md:w-[390px]"><div className="relative"><span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#68736F]">⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Producto, SKU o código de barras" className="field pl-10"/></div></div>}</div>
  {msg&&<div className="mx-4 mt-4 rounded-2xl border border-[#143E35]/10 bg-[#F3F7F5] p-4 text-sm font-semibold text-[#143E35]">{msg}</div>}
  {tab==="stock"&&<div className="p-3 md:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-extrabold text-[#143E35]">Existencias actuales</h2><p className="text-xs text-[#68736F]">{filtered.length} SKU{filtered.length===1?"":"s"} visibles</p></div><button onClick={load} className="rounded-full border border-[#143E35]/15 px-4 py-2 text-xs font-bold text-[#143E35]">Actualizar</button></div><div className="overflow-hidden rounded-2xl border border-[#143E35]/10"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="head"><tr><th>Producto</th><th>Variante</th><th>SKU</th><th>Código de barras</th><th className="text-right">Existencia</th><th>Estado</th></tr></thead><tbody>{filtered.map(r=>{const isLow=Number(r.stock)<=Number(r.low_stock_threshold);return <tr key={r.variant_id} className="border-t border-[#143E35]/8 transition hover:bg-[#FAFBFA]"><td className="p-4"><div className="font-extrabold text-[#143E35]">{r.product_name}</div><div className="mt-1 text-[10px] uppercase tracking-wide text-[#8A9691]">Producto</div></td><td className="p-4 text-[#4E5E58]">{r.variant_title}{r.is_default&&<span className="ml-2 rounded-full bg-[#EEF2F0] px-2 py-1 text-[9px] font-bold text-[#68736F]">Principal</span>}</td><td className="p-4 font-mono text-xs font-bold text-[#143E35]">{r.sku}</td><td className="p-4 font-mono text-xs text-[#4E5E58]">{r.barcode||"—"}</td><td className="p-4 text-right text-lg font-extrabold text-[#143E35]">{r.stock}</td><td className="p-4"><Status stock={r.stock} threshold={r.low_stock_threshold}/></td></tr>})}</tbody></table></div>{loading&&<div className="p-8 text-center text-sm text-[#68736F]">Actualizando inventario…</div>}{!loading&&filtered.length===0&&<Empty text="No encontramos productos con esa búsqueda."/>}</div></div>}
  {tab==="move"&&<div className="p-4 md:p-6"><div className="mx-auto max-w-3xl"><div className="mb-6"><div className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#C8A86B]">Movimiento de inventario</div><h2 className="mt-1 font-serif text-3xl font-semibold text-[#143E35]">Registrar entrada o salida</h2><p className="mt-2 text-sm text-[#68736F]">Las ventas del POS se descuentan automáticamente. Usa este formulario para recepción, ajustes, mermas o devoluciones.</p></div><form onSubmit={move} className="grid gap-4 rounded-[22px] border border-[#143E35]/10 bg-[#FBFCFB] p-5 md:p-6"><label className="label">Producto / variante<select name="variant" required className="field mt-2"><option value="">Selecciona producto / variante…</option>{rows.map(r=><option key={r.variant_id} value={r.variant_id}>{r.product_name} · {r.variant_title} · {r.sku} · existencia {r.stock}</option>)}</select></label><div className="grid gap-4 md:grid-cols-2"><label className="label">Tipo de movimiento<select name="type" className="field mt-2"><option value="restock">Entrada · compra / recepción</option><option value="adjustment">Entrada · ajuste positivo</option><option value="damage">Salida · daño / merma</option><option value="supplier_return">Salida · devolución a proveedor</option></select></label><label className="label">Cantidad<input name="qty" type="number" min="1" required placeholder="Piezas" className="field mt-2"/></label></div><label className="label">Referencia<input name="reason" minLength={3} required placeholder="Ej. Factura 1258 / recepción proveedor" className="field mt-2"/></label><div className="flex flex-col gap-3 pt-2 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-md text-xs leading-5 text-[#68736F]">Guardaremos existencia anterior, existencia nueva, fecha y referencia en la bitácora.</p><button className="btn">Registrar movimiento</button></div></form></div></div>}
  {tab==="log"&&<div className="p-3 md:p-5"><div className="mb-4"><h2 className="text-lg font-extrabold text-[#143E35]">Bitácora de movimientos</h2><p className="text-xs text-[#68736F]">Historial auditable de cambios de inventario.</p></div><div className="overflow-hidden rounded-2xl border border-[#143E35]/10"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="head"><tr><th>Fecha</th><th>Producto</th><th>Movimiento</th><th className="text-right">Cant.</th><th className="text-right">Antes</th><th className="text-right">Después</th><th>Referencia</th></tr></thead><tbody>{filteredMovements.map(m=><tr key={m.id} className="border-t border-[#143E35]/8 hover:bg-[#FAFBFA]"><td className="p-4 whitespace-nowrap text-xs text-[#68736F]">{new Date(m.created_at).toLocaleString("es-MX")}</td><td className="p-4"><b className="text-[#143E35]">{m.product_name||"Producto"}</b><div className="mt-1 text-xs text-[#68736F]">{m.variant_title||"Principal"} · {m.sku||"—"}</div></td><td className="p-4 font-semibold">{movementLabel[m.movement_type]||m.movement_type}</td><td className={`p-4 text-right font-extrabold ${m.quantity_change<0?"text-[#A33A32]":"text-[#1D6A4B]"}`}>{m.quantity_change>0?"+":""}{m.quantity_change}</td><td className="p-4 text-right">{m.stock_before}</td><td className="p-4 text-right font-extrabold text-[#143E35]">{m.stock_after}</td><td className="p-4 max-w-xs"><div>{m.note||"—"}</div>{(m.pos_sale_id||m.order_id)&&<div className="mt-1 text-xs text-[#68736F]">{m.pos_sale_id?"Venta POS":"Pedido"}</div>}</td></tr>)}</tbody></table></div>{!loading&&filteredMovements.length===0&&<Empty text="Aún no hay movimientos que coincidan con la búsqueda."/>}</div></div>}
  </section>
 </div><style jsx>{`.field{width:100%;border:1px solid rgba(20,62,53,.14);border-radius:13px;padding:12px 14px;background:#fff;outline:none;color:#1e1e1e}.field:focus{border-color:#2f6f5b;box-shadow:0 0 0 3px rgba(47,111,91,.09)}.btn{border:0;border-radius:999px;padding:13px 22px;background:#143e35;color:white;font-size:12px;font-weight:800;cursor:pointer}.label{font-size:11px;font-weight:800;color:#143e35}.head{background:#F3F6F4;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#68736F}.head th{padding:12px 16px}`}</style></main>
}
function Metric({label,value,hint,warn=false}:{label:string;value:number;hint:string;warn?:boolean}){return <div className="rounded-[20px] border border-[#143E35]/10 bg-white p-4 shadow-[0_10px_28px_rgba(20,62,53,.04)] md:p-5"><div className="text-[10px] font-extrabold uppercase tracking-[.08em] text-[#7A8782]">{label}</div><div className={`mt-2 text-3xl font-extrabold ${warn?"text-[#A33A32]":"text-[#143E35]"}`}>{value}</div><div className="mt-1 text-[11px] text-[#8A9691]">{hint}</div></div>}
function Status({stock,threshold}:{stock:number;threshold:number}){const low=Number(stock)<=Number(threshold),empty=Number(stock)<=0;return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1.5 text-[10px] font-extrabold ${low?"bg-[#FDECEA] text-[#A33A32]":"bg-[#E9F5EF] text-[#1D6A4B]"}`}><span className={`h-1.5 w-1.5 rounded-full ${low?"bg-[#C54C42]":"bg-[#2D8A64]"}`}/>{empty?"Agotado":low?"Stock bajo":"Disponible"}</span>}
function Empty({text}:{text:string}){return <div className="p-10 text-center"><div className="text-2xl">⌕</div><p className="mt-2 text-sm font-semibold text-[#68736F]">{text}</p></div>}
