create table if not exists public.storefront_texts (
 key text primary key,
 source_text text not null,
 es text not null,
 en text not null,
 updated_at timestamptz not null default now()
);
alter table public.storefront_texts enable row level security;
grant select on public.storefront_texts to anon, authenticated;
create policy "Public can read storefront copy" on public.storefront_texts for select to anon, authenticated using (true);
insert into public.storefront_texts (key,source_text,es,en) values
('text.5807e17cc35a','Golf seleccionado · Pago seguro · Asesoría personal en Los Cabos','Golf seleccionado · Pago seguro · Asesoría personal en Los Cabos','Curated golf · Secure payment · Personal advice in Los Cabos'),
('text.1c524cd21141','Bien elegido.','Bien elegido.','Well chosen.'),
('text.829ce797c51b','Equipo seleccionado para jugar mejor, con asesoría personal en Los Cabos.','Equipo seleccionado para jugar mejor, con asesoría personal en Los Cabos.','Curated equipment to play better, with personal advice in Los Cabos.'),
('text.99b2ec0247ca','Explorar equipo','Explorar equipo','Explore equipment'),
('text.dbcf4f737c89','Filtros','Filtros','Filters'),
('text.29d3e072e967','Encuentra lo que buscas.','Encuentra lo que buscas.','Find what you need.'),
('text.d6653374fc89','Elegidos por Coque.','Elegidos por Coque.','Chosen by Coque.'),
('text.0e52abc65e55','Una selección corta de equipo que sí llevaríamos al campo.','Una selección corta de equipo que sí llevaríamos al campo.','A short selection of equipment we would take to the course.'),
('text.9e5de8a7a5c2','Cargando selección…','Cargando selección…','Loading selection…'),
('text.2b490eb1e349','Lo nuevo.','Lo nuevo.','What''s new.'),
('text.4ab86423dced','Las incorporaciones más recientes al inventario.','Las incorporaciones más recientes al inventario.','The newest additions to inventory.'),
('text.6d374dd910c0','Tu próximo equipo.','Tu próximo equipo.','Your next equipment.'),
('text.a07b5d1a9a52','Busca, filtra y abre cada producto para ver configuración, condición y disponibilidad.','Busca, filtra y abre cada producto para ver configuración, condición y disponibilidad.','Search, filter and open each product to view configuration, condition and availability.'),
('text.76bac843c51f','Más que equipo.','Más que equipo.','More than equipment.'),
('text.1ab7bfda6fb1','Reparación, trade-in, mantenimiento y entrenamiento con atención directa.','Reparación, intercambio, mantenimiento y entrenamiento con atención directa.','Repair, trade-in, maintenance and training with direct personal service.'),
('text.703382aba5a0','Golf en Los Cabos.','Golf en Los Cabos.','Golf in Los Cabos.'),
('text.9949c7acff25','Tres campos para explorar. Confirma horarios y condiciones directamente con cada club.','Tres campos para explorar. Confirma horarios y condiciones directamente con cada club.','Three courses to explore. Confirm schedules and access directly with each club.'),
('text.4995845d4296','Noticias.','Noticias.','News.'),
('text.0fc42b87a4b5','Tres lecturas breves para tomar mejores decisiones dentro y fuera del campo.','Tres lecturas breves para tomar mejores decisiones dentro y fuera del campo.','Three short reads for better decisions on and off the course.'),
('text.2b5b6d806d77','Golf seleccionado, servicio personal y experiencia local en Los Cabos.','Golf seleccionado, servicio personal y experiencia local en Los Cabos.','Curated golf, personal service and local experience in Los Cabos.'),
('text.d1d3f471293a','Curated golf equipment · Compra segura con Stripe · Atención personalizada en Los Cabos','Curated golf equipment · Compra segura con Stripe · Atención personalizada en Los Cabos','Curated golf equipment · Secure Stripe checkout · Personal service in Los Cabos'),
('text.17a48e2cfde4','Antes de elegir instructor','Antes de elegir instructor','Before choosing an instructor'),
('text.4f35bbc04635','Cuéntanos sobre tu juego.','Cuéntanos sobre tu juego.','Tell us about your game.'),
('text.093ec4e0a9ae','Con estos datos podremos orientarte mejor y entender qué buscan los golfistas que llegan a UP AND DOWN.','Con estos datos podremos orientarte mejor y entender qué buscan los golfistas que llegan a UP AND DOWN.','This helps us guide you better and understand what golfers coming to UP AND DOWN are looking for.'),
('text.e68491e91c7c','Nombre','Nombre','Name'),
('text.f07e1b890b9b','Tu nombre','Tu nombre','Your name'),
('text.a4781bd250b3','Teléfono / WhatsApp','Teléfono / WhatsApp','Phone / WhatsApp'),
('text.572c0e4bf140','Nivel de juego','Nivel de juego','Playing level'),
('text.888fa8231769','Selecciona tu nivel','Selecciona tu nivel','Select your level'),
('text.e1bf35d5b916','Estoy empezando','Estoy empezando','I''m just starting'),
('text.0daca1d04c78','Principiante','Principiante','Beginner'),
('text.66ca7ed41767','Intermedio','Intermedio','Intermediate'),
('text.980a92c1058f','Avanzado','Avanzado','Advanced'),
('text.98529ee2467d','Competitivo','Competitivo','Competitive'),
('text.c07c2de651d9','¿Qué te gustaría mejorar?','¿Qué te gustaría mejorar?','What would you like to improve?'),
('text.ffc16236056e','Selecciona un objetivo','Selecciona un objetivo','Select a goal'),
('text.fad4a9a4ec99','Empezar desde cero','Empezar desde cero','Start from scratch'),
('text.f52dbab970fb','Consistencia del swing','Consistencia del movimiento de golpe','Swing consistency'),
('text.76653c82e2d5','Más distancia / driver','Más distancia con el palo de salida','More distance with the driver'),
('text.eb93b38efad8','Hierros y precisión','Hierros y precisión','Irons and accuracy'),
('text.d9a881709c46','Juego corto','Juego corto','Short game'),
('text.56e286e60201','Estrategia en campo','Estrategia en campo','Course strategy'),
('text.ada1c1ef4a9e','Otro','Otro','Other'),
('text.50d22e5b116d','Cuéntanos un poco más','Cuéntanos un poco más','Tell us a little more'),
('text.c27a95feee57','Ej. Quiero ser más consistente con el driver y perder menos golpes desde el tee.','Ej. Quiero ser más consistente con el palo de salida y perder menos golpes desde el soporte para pelota.','E.g. I want to be more consistent with my driver and lose fewer shots off the tee.'),
('text.48cec6b14732','Autorizo a UP AND DOWN a contactarme por WhatsApp, SMS o llamada para atender mi solicitud de clases y dar seguimiento relacionado con servicios de golf. Mi información será utilizada para gestionar esta solicitud, atención comercial y análisis interno; no será vendida a terceros. Puedo solicitar dejar de recibir mensajes en cualquier momento.','Autorizo a UP AND DOWN a contactarme por WhatsApp, SMS o llamada para atender mi solicitud de clases y dar seguimiento relacionado con servicios de golf. Mi información será utilizada para gestionar esta solicitud, atención comercial y análisis interno; no será vendida a terceros. Puedo solicitar dejar de recibir mensajes en cualquier momento.','I authorize UP AND DOWN to contact me by WhatsApp, SMS or phone to handle my lesson request and follow up on related golf services. My information will be used to manage this request, commercial service and internal analytics; it will not be sold to third parties. I may ask to stop receiving messages at any time.'),
('text.0a055ceb782a','Guardar y ver instructores','Guardar y ver instructores','Save and view instructors'),
('text.b8ca9ce5655f','Instructores UP AND DOWN','Instructores UP AND DOWN','UP AND DOWN instructors'),
('text.6c00609acd48','Elige con quién quieres trabajar.','Elige con quién quieres trabajar.','Choose your instructor.'),
('text.a6e8b65f103f','Tus datos quedaron guardados. Ahora puedes contactar directamente al instructor que prefieras.','Tus datos quedaron guardados. Ahora puedes contactar directamente al instructor que prefieras.','Your information was saved. You can now contact the instructor you prefer directly.'),
('text.7281d5cd6528','Profesional e instructor','Profesional e instructor','Golf professional & instructor'),
('text.767d57e15d38','Planear una clase con Rodrigo','Planear una clase con Rodrigo','Plan a lesson with Rodrigo'),
('text.bf5e7d5e0014','Planear una clase con Mario','Planear una clase con Mario','Plan a lesson with Mario'),
('text.1ef6032f5d0f','Cuéntanos un poco más (opcional)','Cuéntanos un poco más (opcional)','Tell us a little more (optional)'),
('text.726b7c89ce79','¿Quieres registrar a otra persona?','¿Quieres registrar a otra persona?','Would you like to register someone else?'),
('text.e174a490d6e2','Puedes registrar a otra persona y los instructores seguirán disponibles mientras completas sus datos.','Puedes registrar a otra persona y los instructores seguirán disponibles mientras completas sus datos.','You can register someone else while instructors remain available below.'),
('text.98d14d37df57','Registrar a otra persona','Registrar a otra persona','Register another person'),
('text.5c3714236aa2','Novedades','Novedades','New arrivals'),
('text.754711c62a0c','Tienda','Tienda','Shop'),
('text.941a1528f555','Categorías','Categorías','Categories'),
('text.51d3e479f4c1','Servicios','Servicios','Services'),
('text.e98cfda46ebd','Campos de golf','Campos de golf','Golf courses'),
('text.85a504e0900d','Equipo nuevo, seminuevo y piezas seleccionadas para tu juego, con asesoría personal en Los Cabos.','Equipo nuevo, seminuevo y piezas seleccionadas para tu juego, con asesoría personal en Los Cabos.','New, pre-owned and curated golf equipment for your game, with personal advice in Los Cabos.'),
('text.0a920f7b3ace','Explorar colección','Explorar colección','Explore collection'),
('text.6118b92a6aff','Hierros','Hierros','Irons'),
('text.b03ccbdfb764','Seminuevos','Seminuevos','Pre-owned'),
('text.8057acefccf1','Descubre','Descubre','Discover'),
('text.dfae18ae60dd','Buscar productos','Buscar productos','Search products'),
('text.e8149c028cae','Categoría','Categoría','Category'),
('text.fad5dfe76f29','Todas las categorías','Todas las categorías','All categories'),
('text.dd580e8da42a','Condición','Condición','Condition'),
('text.531759e43657','Cualquier condición','Cualquier condición','Any condition'),
('text.a959909c5018','Nuevo','Nuevo','New'),
('text.e67260660938','Seminuevo','Seminuevo','Pre-owned'),
('text.896509453753','Más filtros','Más filtros','More filters'),
('text.4f1f1abf7513','Categoría: todas','Categoría: todas','Category: all'),
('text.a2f7de44316b','Condición: cualquiera','Condición: cualquiera','Condition: any'),
('text.00681caabd89','Todas las marcas','Todas las marcas','All brands'),
('text.df7a0ef63dd1','Cualquier mano','Cualquier mano','Any hand'),
('text.7866e32a01ae','Cualquier flex','Cualquier flexibilidad','Any flex'),
('text.a7487585e439','Cualquier loft','Cualquier ángulo de la cara','Any loft'),
('text.34ba221db5bf','Relevancia','Relevancia','Relevance'),
('text.c41e9086ad8b','Más recientes','Más recientes','Newest'),
('text.500a158938ee','Precio: menor a mayor','Precio: menor a mayor','Price: low to high'),
('text.103ecaf0aa8c','Precio: mayor a menor','Precio: mayor a menor','Price: high to low'),
('text.9c3186f9286a','Los filtros de mano, loft y flex aparecen automáticamente cuando esos datos existen en las especificaciones del producto.','Los filtros de mano, ángulo y flexibilidad aparecen cuando esos datos existen en las especificaciones del producto.','Hand, loft and flex filters appear when those specifications are available.'),
('text.2f58c8e010ab','Borrar filtros','Borrar filtros','Clear filters'),
('text.a4ef6d42fe91','Aplicar filtros y ver productos','Aplicar filtros y ver productos','Apply filters & view products'),
('text.32a144767a8d','Tu Golf Advisor','Tu Asesor de golf','Your Golf Advisor'),
('text.bf4a05f64afc','Consultar con mi asesor','Consultar con mi asesor','Contact my advisor'),
('text.3791c3e82395','Seminuevos seleccionados','Seminuevos seleccionados','Curated pre-owned'),
('text.b02db1fc2be9','Recién llegados','Recién llegados','New arrivals'),
('text.bdcf70109b40','Recién llegados.','Recién llegados.','New arrivals.'),
('text.16dba9bbea01','Una selección dinámica de los productos más recientes y piezas destacadas del catálogo.','Una selección dinámica de los productos más recientes y piezas destacadas del catálogo.','A dynamic selection of the newest products and highlighted pieces in the catalog.'),
('text.89f8ac702573','Cargando novedades…','Cargando novedades…','Loading new arrivals…'),
('text.d32bb1e1816e','Compra por categoría.','Compra por categoría.','Shop by category.'),
('text.50ff3f008d40','Ver toda la tienda','Ver toda la tienda','View full shop'),
('text.09d394f52305','El equipo correcto cambia el juego.','El equipo correcto cambia el juego.','The right equipment changes the game.'),
('text.6991aed22f8e','Consulta disponibilidad, compara condiciones y arma tu selección con inventario actualizado.','Consulta disponibilidad, compara condiciones y arma tu selección con inventario actualizado.','Check availability, compare conditions and build your selection with updated inventory.'),
('text.6f56e80181b5','Filtra sin salir del catálogo','Filtra sin salir del catálogo','Filter without leaving the catalog'),
('text.b02e01b412e5','· ajusta tu búsqueda y resultados aquí mismo','· ajusta tu búsqueda y resultados aquí mismo','· refine your search and results right here'),
('text.aed00de88ed8','Filtrar catálogo','Filtrar catálogo','Filter catalog'),
('text.ef722a671a09','Aplicar filtros','Aplicar filtros','Apply filters'),
('text.801a8a1be166','Inventario actualizado','Inventario actualizado','Updated inventory'),
('text.a84531e6aba8','Pago seguro con Stripe','Pago seguro con Stripe','Secure Stripe payment'),
('text.eb0011640c01','Asesoría personal','Asesoría personal','Personal advice'),
('text.c2e172d42adf','Consultando catálogo…','Consultando catálogo…','Checking catalog…'),
('text.d3126bccacc0','Limpiar filtros','Limpiar filtros','Clear filters'),
('text.fb48f4168535','Conectando con el catálogo…','Conectando con el catálogo…','Connecting to catalog…'),
('text.2aca49f34ebe','Detalles que bajan golpes.','Detalles que bajan golpes.','Details that can save strokes.'),
('text.cedc8d71a76b','Pelotas, guantes, accesorios y piezas seleccionadas para jugar con más confianza. Menos ruido; mejores decisiones.','Pelotas, guantes, accesorios y piezas seleccionadas para jugar con más confianza. Menos ruido; mejores decisiones.','Balls, gloves, accessories and selected essentials to play with more confidence. Less noise; better decisions.'),
('text.37d9fe706f8e','Explorar pelotas y accesorios','Explorar pelotas y accesorios','Explore balls & accessories'),
('text.c46fb4d63009','Servicios UP AND DOWN','Servicios UP AND DOWN','UP AND DOWN Services'),
('text.cab2c84a881c','Más que equipo. Acompañamiento para tu juego.','Más que equipo. Acompañamiento para tu juego.','More than equipment. Support for your game.'),
('text.1b63993c7b03','Revisión, valoración, mantenimiento y entrenamiento personalizado con atención directa y procesos sencillos.','Revisión, valoración, mantenimiento y entrenamiento personalizado con atención directa y procesos sencillos.','Inspection, trade-in evaluation, maintenance and personalized training with direct service and a simple process.'),
('text.aa822a4ecdb0','Diagnóstico inicial sin costo','Diagnóstico inicial sin costo','Complimentary initial assessment'),
('text.3fa1a1f63f99','Reparación de equipo','Reparación de equipo','Equipment repair'),
('text.dbe67d1e4503','¿Tu equipo presenta desgaste, daño o alguna falla? Llévalo a la tienda para una revisión inicial sin costo. Evaluaremos su condición y te explicaremos las alternativas disponibles antes de realizar cualquier trabajo.','¿Tu equipo presenta desgaste, daño o alguna falla? Llévalo a la tienda para una revisión inicial sin costo. Evaluaremos su condición y te explicaremos las alternativas disponibles antes de realizar cualquier trabajo.','Is your equipment showing wear, damage or a malfunction? Bring it to the shop for a complimentary initial assessment. We will evaluate its condition and explain the available options before any work begins.'),
('text.ff4046814090','Revisión física del equipo.','Revisión física del equipo.','Physical equipment inspection.'),
('text.63c64a5910d6','Diagnóstico inicial sin compromiso.','Diagnóstico inicial sin compromiso.','Initial assessment with no commitment.'),
('text.6ad604cfc8d6','Cotización previa antes de iniciar cualquier reparación.','Cotización previa antes de iniciar cualquier reparación.','Quote provided before any repair begins.'),
('text.6cc23a3bdeed','Solicitar información','Solicitar información','Request information'),
('text.8e03f755ad8b','La reparación y el precio final se confirman únicamente después de revisar físicamente el equipo.','La reparación y el precio final se confirman únicamente después de revisar físicamente el equipo.','The repair scope and final price are confirmed only after a physical inspection of the equipment.'),
('text.85bdf2b43bac','Valoración presencial','Valoración presencial','In-store evaluation'),
('text.72fded6a939e','Intercambios con tienda','Intercambios con tienda','Trade-ins'),
('text.4ae2df301963','Trae tus palos, bolsa o equipo participante para una valoración presencial. Revisaremos marca, modelo, condición, antigüedad y demanda para determinar si puede considerarse como parte de pago en la compra de otro producto.','Trae tus palos, bolsa o equipo participante para una valoración presencial. Revisaremos marca, modelo, condición, antigüedad y demanda para determinar si puede considerarse como parte de pago en la compra de otro producto.','Bring your clubs, bag or eligible equipment for an in-store evaluation. We will review brand, model, condition, age and demand to determine whether it can be considered toward the purchase of another product.'),
('text.5794d176bd7f','Valoración basada en condición real y demanda.','Valoración basada en condición real y demanda.','Evaluation based on actual condition and demand.'),
('text.89f3aa005828','Posibilidad de aplicar el valor como crédito en tienda.','Posibilidad de aplicar el valor como crédito en tienda.','Potential to apply the value as store credit.'),
('text.13ba39996f23','Aceptación sujeta a revisión y elegibilidad del equipo.','Aceptación sujeta a revisión y elegibilidad del equipo.','Acceptance is subject to inspection and equipment eligibility.'),
('text.a4522b9e41f5','Valorar mi equipo','Valorar mi equipo','Evaluate my equipment'),
('text.c4ab933a5677','La recepción del equipo no garantiza su aceptación ni un valor específico.','La recepción del equipo no garantiza su aceptación ni un valor específico.','Receiving the equipment does not guarantee acceptance or a specific value.'),
('text.9efdc0bdc028','Prevención y cuidado','Prevención y cuidado','Care & prevention'),
('text.16f2c7120cd3','Mantenimiento','Mantenimiento','Maintenance'),
('text.2cbc70a78526','Mantén tu equipo listo para la siguiente ronda. Revisamos grips, limpieza general, ajustes básicos y señales de desgaste para recomendar el mantenimiento adecuado.','Mantén tu equipo listo para la siguiente ronda. Revisamos empuñaduras, limpieza general, ajustes básicos y señales de desgaste para recomendar el mantenimiento adecuado.','Keep your equipment ready for the next round. We inspect grips, perform general cleaning, basic adjustments and look for signs of wear to recommend the right maintenance.'),
('text.96cb90b76f82','Limpieza general de cabezas y varillas.','Limpieza general de cabezas y varillas.','General cleaning of clubheads and shafts.'),
('text.47205131f1a0','Revisión y posible cambio de grips.','Revisión y posible cambio de empuñaduras.','Grip inspection and replacement when needed.'),
('text.0ab7d17a948e','Inspección visual de desgaste y ajustes menores.','Inspección visual de desgaste y ajustes menores.','Visual wear inspection and minor adjustments.'),
('text.a1ea4856be22','Consultar mantenimiento','Consultar mantenimiento','Ask about maintenance'),
('text.44c5943a945f','El alcance del servicio se determina después de revisar el estado actual del equipo.','El alcance del servicio se determina después de revisar el estado actual del equipo.','The service scope is determined after reviewing the equipment''s current condition.'),
('text.d9dd43553531','Entrenamiento personalizado','Entrenamiento personalizado','Personalized training'),
('text.a8fa3a8626a9','Clase de entrenamiento','Clase de entrenamiento','Training session'),
('text.079f7b8685d1','Sesiones personalizadas para trabajar técnica, consistencia y toma de decisiones. Elige un horario disponible y comparte tus objetivos para preparar mejor la clase.','Sesiones personalizadas para trabajar técnica, consistencia y toma de decisiones. Elige un horario disponible y comparte tus objetivos para preparar mejor la clase.','Personalized sessions focused on technique, consistency and decision-making. Choose an available time and share your goals so the session can be better prepared.'),
('text.612ab793c335','Opciones para nivel principiante, intermedio o avanzado.','Opciones para nivel principiante, intermedio o avanzado.','Options for beginner, intermediate or advanced players.'),
('text.77c98cf0ce5e','Objetivos posibles: swing, driver, juego corto, putting o consistencia general.','Objetivos posibles: movimiento de golpe, palo de salida, juego corto, juego de precisión o consistencia general.','Possible goals: swing, driver, short game, putting or overall consistency.'),
('text.35d6cfd130fc','Confirmación y seguimiento mediante HighLevel.','Confirmación y seguimiento mediante HighLevel.','Confirmation and follow-up through HighLevel.'),
('text.f6db529a4e7f','Consultar por WhatsApp','Consultar por WhatsApp','Ask on WhatsApp'),
('text.1fd96d2249e7','Juega donde el desierto toca el mar.','Juega donde el desierto toca el mar.','Play where the desert meets the sea.'),
('text.bc2182ab61e2','Directorio informativo para ubicar algunos de los campos más representativos. Los horarios y condiciones de acceso pueden cambiar; consulta siempre al club.','Directorio informativo para ubicar algunos de los campos más representativos. Los horarios y condiciones de acceso pueden cambiar; consulta siempre al club.','An informative directory to help you locate some of the area''s most representative courses. Hours and access conditions may change; always confirm directly with the club.'),
('text.12105e2d83e7','San José del Cabo','San José del Cabo','San José del Cabo'),
('text.ccef4e982951','Km 7.5 Carretera Transpeninsular. Campo Jack Nicklaus Signature con 27 hoyos y vistas al mar y al desierto.','Km 7.5 Carretera Transpeninsular. Campo Jack Nicklaus Signature con 27 hoyos y vistas al mar y al desierto.','Km 7.5 Transpeninsular Highway. A 27-hole Jack Nicklaus Signature course with ocean and desert views.'),
('text.2ca5a6f9a74f','Cómo llegar','Cómo llegar','Directions'),
('text.527805e420cb','Sitio oficial','Sitio oficial','Official website'),
('text.f2d50e4a137b','Corredor Turístico','Corredor Turístico','Tourist Corridor'),
('text.080b31b53dd2','Km 19.5 Carretera Transpeninsular. Trazado de Robert Trent Jones Jr. con fairways amplios y vistas al Mar de Cortés.','Km 19.5 Carretera Transpeninsular. Trazado de Robert Trent Jones Jr. con fairways amplios y vistas al Mar de Cortés.','Km 19.5 Transpeninsular Highway. A Robert Trent Jones Jr. layout with generous fairways and Sea of Cortez views.'),
('text.15b7d9d8fa42','Complejo de 27 hoyos diseñado por Jack Nicklaus y Greg Norman, a pocos minutos del centro histórico de San José del Cabo.','Complejo de 27 hoyos diseñado por Jack Nicklaus y Greg Norman, a pocos minutos del centro histórico de San José del Cabo.','A 27-hole complex designed by Jack Nicklaus and Greg Norman, just minutes from historic downtown San José del Cabo.'),
('text.8d18a240c74e','Historias para jugar mejor.','Historias para jugar mejor.','Stories to play better.'),
('text.3172a5b26967','Guías breves creadas para disfrutar el golf en Los Cabos con mejores decisiones, más preparación y menos improvisación.','Guías breves creadas para disfrutar el golf en Los Cabos con mejores decisiones, más preparación y menos improvisación.','Short guides created to help you enjoy golf in Los Cabos with better decisions, better preparation and less improvisation.'),
('text.8f4740c5c98e','Destino · Los Cabos','Destino · Los Cabos','Destination · Los Cabos'),
('text.d2289bb50a12','Cómo elegir el campo ideal para tu ronda.','Cómo elegir el campo ideal para tu ronda.','How to choose the right course for your round.'),
('text.942b43b75c20','Mar, desierto, viento y diferentes niveles de dificultad: cada campo de Los Cabos ofrece una experiencia distinta.','Mar, desierto, viento y diferentes niveles de dificultad: cada campo de Los Cabos ofrece una experiencia distinta.','Ocean, desert, wind and different levels of difficulty: every course in Los Cabos offers a different experience.'),
('text.557e23b3a597','Leer artículo','Leer artículo','Read article'),
('text.2b469ab83ebb','Cerrar artículo','Cerrar artículo','Close article'),
('text.35be4eaef272','Antes de elegir un campo, piensa primero en la experiencia que buscas. Una ronda panorámica no siempre es la más indulgente, y un trazado técnico puede ser excelente para un jugador experimentado, pero frustrante para quien apenas está retomando el juego.','Antes de elegir un campo, piensa primero en la experiencia que buscas. Una ronda panorámica no siempre es la más indulgente, y un trazado técnico puede ser excelente para un jugador experimentado, pero frustrante para quien apenas está retomando el juego.','Before choosing a course, first think about the experience you want. A scenic round is not always the most forgiving, and a technical layout may be excellent for an experienced player but frustrating for someone just getting back into the game.'),
('text.fbb04c1aaf6f','Experiencia','Experiencia','Experience'),
('text.4e1f088d8a0c','Consulta dificultad, tipo de terreno y ritmo estimado de juego.','Consulta dificultad, tipo de terreno y ritmo estimado de juego.','Check difficulty, terrain type and expected pace of play.'),
('text.6587df9c6165','Clima','Clima','Weather'),
('text.4aaffa5acc15','En Los Cabos, el viento y la hora de salida pueden cambiar completamente la ronda.','En Los Cabos, el viento y la hora de salida pueden cambiar completamente la ronda.','In Los Cabos, wind and tee time can completely change the round.'),
('text.94573b18ff3f','Logística','Logística','Logistics'),
('text.6e69f92d1045','Revisa ubicación, acceso, código de vestimenta y políticas del club.','Revisa ubicación, acceso, código de vestimenta y políticas del club.','Check location, access, dress code and club policies.'),
('text.f9431d879e0e','La recomendación de Coque','La recomendación de Coque','Coque''s recommendation'),
('text.1aabeeff2293','Para una primera visita, prioriza una combinación equilibrada de paisaje, accesibilidad y nivel de dificultad. Cuando ya conozcas cómo juegas con el viento y la firmeza del terreno local, será más fácil buscar retos técnicos específicos.','Para una primera visita, prioriza una combinación equilibrada de paisaje, accesibilidad y nivel de dificultad. Cuando ya conozcas cómo juegas con el viento y la firmeza del terreno local, será más fácil buscar retos técnicos específicos.','For a first visit, prioritize a balanced combination of scenery, accessibility and difficulty. Once you understand how your game reacts to the local wind and firm conditions, it will be easier to seek out specific technical challenges.'),
('text.bc36a36f8c0c','Los horarios, condiciones de acceso y disponibilidad pueden cambiar. UP AND DOWN funciona únicamente como directorio informativo; confirma siempre los detalles directamente con el campo.','Los horarios, condiciones de acceso y disponibilidad pueden cambiar. UP AND DOWN funciona únicamente como directorio informativo; confirma siempre los detalles directamente con el campo.','Hours, access conditions and availability may change. UP AND DOWN serves only as an informational directory; always confirm details directly with the course.'),
('text.a9fffc300fc6','Cómo elegir un driver sin comprar solo distancia.','Cómo elegir un palo de salida sin comprar solo distancia.','How to choose a driver without buying distance alone.'),
('text.3bf3d97ade93','La cabeza más nueva o el loft más bajo no garantizan mejores salidas. El objetivo real es encontrar consistencia.','La cabeza más nueva o el ángulo de la cara más bajo no garantizan mejores salidas. El objetivo real es encontrar consistencia.','The newest head or lowest loft does not guarantee better drives. The real goal is consistency.'),
('text.e42fe095936e','Un buen driver debe ayudarte a repetir un patrón de vuelo útil, no solamente producir un golpe espectacular de vez en cuando. Loft, flexibilidad de la varilla, longitud, peso y distribución de masa trabajan juntos.','Un buen palo de salida debe ayudarte a repetir un patrón de vuelo útil, no solamente producir un golpe espectacular de vez en cuando. ángulo de la cara, flexibilidad de la varilla, longitud, peso y distribución de masa trabajan juntos.','A good driver should help you repeat a useful ball flight, not just produce one spectacular shot once in a while. Loft, shaft flex, length, weight and mass distribution all work together.'),
('text.bedb2ac693a7','Más loft puede facilitar el lanzamiento y reducir la pérdida de distancia por golpes bajos.','Más ángulo de la cara puede facilitar el lanzamiento y reducir la pérdida de distancia por golpes bajos.','More loft can help launch the ball and reduce distance loss from low strikes.'),
('text.739b81dbf204','Varilla','Varilla','Shaft'),
('text.3a4ba0b51126','El flex correcto debe acompañar tu velocidad y tempo, no tu ego. El ego rara vez encuentra fairway.','El flexibilidad correcto debe acompañar tu velocidad y tempo, no tu ego. El ego rara vez encuentra calle del campo.','The right flex should match your speed and tempo, not your ego. Ego rarely finds the fairway.'),
('text.dc41d8dc5276','Perdón','Perdón','Forgiveness'),
('text.a1be3b1f0d45','Una cabeza estable conserva más velocidad cuando el impacto no ocurre en el centro.','Una cabeza estable conserva más velocidad cuando el impacto no ocurre en el centro.','A stable head preserves more speed when impact is off-center.'),
('text.1c4143ab96ad','Prioriza dispersión','Prioriza dispersión','Prioritize dispersion'),
('text.2c8c2711b23a','Compara la distancia promedio y la dispersión, no únicamente el golpe más largo. Diez metros menos dentro del fairway suelen valer más que veinte metros adicionales desde una posición complicada.','Compara la distancia promedio y la dispersión, no únicamente el golpe más largo. Diez metros menos dentro del calle del campo suelen valer más que veinte metros adicionales desde una posición complicada.','Compare average distance and dispersion, not only your longest shot. Ten fewer meters from the fairway are often worth more than twenty extra meters from trouble.'),
('text.de5429891325','Cuando sea posible, prueba distintas configuraciones antes de decidir. La selección correcta debe sentirse repetible y cómoda durante toda la ronda.','Cuando sea posible, prueba distintas configuraciones antes de decidir. La selección correcta debe sentirse repetible y cómoda durante toda la ronda.','Whenever possible, test different configurations before deciding. The right setup should feel repeatable and comfortable throughout the round.'),
('text.6bbc3940801c','Qué llevar para jugar bajo el clima de Los Cabos.','Qué llevar para jugar bajo el clima de Los Cabos.','What to carry for golf in Los Cabos weather.'),
('text.36fe98f76dd2','Sol intenso, viento y cambios de temperatura entre la mañana y la tarde exigen una bolsa bien planeada.','Sol intenso, viento y cambios de temperatura entre la mañana y la tarde exigen una bolsa bien planeada.','Strong sun, wind and temperature changes from morning to afternoon call for a well-planned golf bag.'),
('text.64d157d7d7c0','Prepararte para el entorno ayuda tanto como elegir el palo correcto. Además de tu equipo habitual, considera protección solar, hidratación, capas ligeras y accesorios que mantengan el agarre estable.','Prepararte para el entorno ayuda tanto como elegir el palo correcto. Además de tu equipo habitual, considera protección solar, hidratación, capas ligeras y accesorios que mantengan el agarre estable.','Preparing for the environment matters almost as much as choosing the right club. Along with your usual equipment, consider sun protection, hydration, light layers and accessories that keep your grip secure.'),
('text.16fe2a39cd34','Protección','Protección','Protection'),
('text.45feb68ff7ba','Gorra, lentes, bloqueador y manga ligera para exposición prolongada.','Gorra, lentes, bloqueador y manga ligera para exposición prolongada.','Cap, sunglasses, sunscreen and a light sleeve for prolonged exposure.'),
('text.6566ac8718cc','Agarre','Agarre','Grip'),
('text.615a46866c80','Guante adicional y toalla seca para mantener control cuando aumenta el calor.','Guante adicional y toalla seca para mantener control cuando aumenta el calor.','An extra glove and dry towel help maintain control as temperatures rise.'),
('text.9a0cc671957e','Hidratación','Hidratación','Hydration'),
('text.38f9709faf9e','Agua y electrolitos antes de sentir sed; el clima seco puede engañar.','Agua y electrolitos antes de sentir sed; el clima seco puede engañar.','Water and electrolytes before you feel thirsty; the dry climate can be deceptive.'),
('text.35b68067f202','Menos peso, mejor selección','Menos peso, mejor selección','Less weight, better selection'),
('text.d6cd9a1acbee','No necesitas llenar todos los bolsillos. Lleva solamente lo que resuelva una necesidad real durante la ronda y revisa previamente si el campo ofrece agua, práctica, restaurante o tienda.','No necesitas llenar todos los bolsillos. Lleva solamente lo que resuelva una necesidad real durante la ronda y revisa previamente si el campo ofrece agua, práctica, restaurante o tienda.','You do not need to fill every pocket. Carry only what solves a real need during the round and check in advance whether the course offers water, practice facilities, a restaurant or a shop.'),
('text.7fd2f872d6ef','En salidas tempranas puede sentirse fresco, mientras que al mediodía la radiación aumenta considerablemente. Una capa ligera y transpirable suele ser la mejor solución.','En salidas tempranas puede sentirse fresco, mientras que al mediodía la radiación aumenta considerablemente. Una capa ligera y transpirable suele ser la mejor solución.','Early tee times can feel cool, while midday sun exposure rises considerably. A light, breathable layer is often the best solution.'),
('text.ea84207b8c9d','Envío seguro','Envío seguro','Secure shipping'),
('text.6c5d4e398ce8','Coordinación personalizada.','Coordinación personalizada.','Personalized coordination.'),
('text.a0d2f4e5cd4c','Pago seguro','Pago seguro','Secure payment'),
('text.05430cdd6473','Procesado con Stripe.','Procesado con Stripe.','Processed with Stripe.'),
('text.ba803b6b827b','Atención personal','Atención personal','Personal service'),
('text.b90e20339d4b','Por golfistas, para golfistas.','Por golfistas, para golfistas.','By golfers, for golfers.'),
('text.8df296cb7950','Disponibilidad conciliada antes del pago.','Disponibilidad conciliada antes del pago.','Availability reconciled before payment.'),
('text.54cd0f47377d','Equipamiento premium para golfistas que viven el juego con pasión, precisión y estilo.','Equipamiento premium para golfistas que viven el juego con pasión, precisión y estilo.','Premium equipment for golfers who live the game with passion, precision and style.'),
('text.86f199617016','Todos los productos','Todos los productos','All products'),
('text.2399a27d8702','Conéctate','Conéctate','Connect'),
('text.f9ae7caca560','Golf Concierge','Asesor de golf','Golf Concierge'),
('text.50ef0c3e94a1','Consulta equipo y configuración','Consulta equipo y configuración','Ask about equipment & setup'),
('text.a7349b7cad9f','Tu carrito','Tu carrito','Your cart'),
('text.2d7e7d226a51','productos','productos','products'),
('text.a62405e2cefb','Buscar','Buscar','Search'),
('text.6cc222f7f7c8','Asesor','Asesor','Advisor'),
('text.a405a781271a','Carrito','Carrito','Cart'),
('text.97f7359ed801','Subtotal','Subtotal','Subtotal'),
('text.6a74d1529502','Finalizar compra segura','Finalizar compra segura','Secure checkout'),
('text.8ecf2786e31b','Inventario validado antes de continuar a Stripe.','Inventario validado antes de continuar a Stripe.','Inventory is validated before continuing to Stripe.'),
('text.25ddaffa0f96','Precio expresado en pesos mexicanos (MXN).','Precio expresado en pesos mexicanos (MXN).','Price shown in Mexican pesos (MXN).'),
('text.63c0fc22dab2','Para qué jugador','Para qué jugador','Player profile'),
('text.806f281f713d','Configuración','Configuración','Configuration'),
('text.bf1bcbd811b3','Condición y disponibilidad','Condición y disponibilidad','Condition & availability'),
('text.9d2d6bed5d60','Producto','Producto','Product'),
('text.f21858bfd76f','Consulta detalles con nuestro equipo.','Consulta detalles con nuestro equipo.','Ask our team for details.'),
('text.264396ec6d7c','Disponible','Disponible','Available'),
('text.75e94de4cc49','Agregar al carrito','Agregar al carrito','Add to cart'),
('text.7534214e656f','Consultar este equipo','Consultar este equipo','Ask about this equipment'),
('text.b2d2420e886f','Preguntar sobre este equipo','Preguntar sobre este equipo','Ask about this equipment'),
('text.9ba40ee66cba','¿Tienes equipo para intercambiar?','¿Tienes equipo para intercambiar?','Have equipment to trade in?'),
('text.0ccfedeb0404','Pago confirmado','Pago confirmado','Payment confirmed'),
('text.69c1a6b6a502','Tu pedido está en juego.','Tu pedido está en juego.','Your order is in play.'),
('text.ab5019d23022','Recibimos tu compra correctamente. Nuestro equipo continuará con la preparación y coordinación de entrega.','Recibimos tu compra correctamente. Nuestro equipo continuará con la preparación y coordinación de entrega.','We received your purchase. Our team will prepare your order and coordinate delivery.'),
('text.9758b5345fd9','Continuar comprando','Continuar comprando','Continue shopping'),
('text.7e2f64f58cbb','Novedades y ofertas.','Novedades y ofertas.','New arrivals & offers.'),
('text.7ff0f11f119f','Lo más reciente del inventario y oportunidades con precio especial.','Lo más reciente del inventario y oportunidades con precio especial.','The latest inventory and selected special offers.'),
('text.83ec49cb1d9c','Cargando novedades y ofertas…','Cargando novedades y ofertas…','Loading new arrivals & offers…'),
('text.58138b121bd8','Reparación, intercambio, mantenimiento, clases, restauraciones y acceso a GHIN con atención directa.','Reparación, intercambio, mantenimiento, clases, restauraciones y acceso a GHIN con atención directa.','Repair, trade-in, maintenance, lessons, restorations and GHIN access with direct service.'),
('text.085213893f5f','Clases de golf','Clases de golf','Golf lessons'),
('text.aba339d0360d','Sesiones para trabajar técnica, consistencia y toma de decisiones según tu nivel y objetivos.','Sesiones para trabajar técnica, consistencia y toma de decisiones según tu nivel y objetivos.','Sessions focused on technique, consistency and decision-making based on your level and goals.'),
('text.7d2d3c04a039','Principiante, intermedio o avanzado.','Principiante, intermedio o avanzado.','Beginner, intermediate or advanced.'),
('text.278999f5f14b','Swing, driver, juego corto o putting.','movimiento de golpe, palo de salida, juego corto o juego de precisión.','Swing, driver, short game or putting.'),
('text.bf7134431100','Agenda y seguimiento directo.','Agenda y seguimiento directo.','Direct scheduling and follow-up.'),
('text.5cb2a90c1d6e','Restauraciones de Putters','Restauraciones de palos de precisión','Putter restorations'),
('text.f9c1e7eab688','Recupera una pieza especial','Recupera una pieza especial','Restore a special piece'),
('text.fb00c7fafb1a','Evaluamos tu putter para orientarte sobre opciones de restauración, acabado y recuperación estética de acuerdo con su estado actual.','Evaluamos tu palo de precisión para orientarte sobre opciones de restauración, acabado y recuperación estética de acuerdo con su estado actual.','We assess your putter and guide you through restoration, finish and cosmetic options based on its condition.'),
('text.6c996c89b790','Revisión previa del putter.','Revisión previa del palo de precisión.','Initial putter inspection.'),
('text.33b2284a781e','Opciones según material y condición.','Opciones según material y condición.','Options based on material and condition.'),
('text.257a0adfabe7','Cotización antes de iniciar.','Cotización antes de iniciar.','Quote before work begins.'),
('text.8c102abdf436','Consultar restauración','Consultar restauración','Ask about restoration'),
('text.12a0fdbc3d77','La viabilidad del trabajo se confirma después de revisar la pieza.','La viabilidad del trabajo se confirma después de revisar la pieza.','Feasibility is confirmed after inspecting the piece.'),
('text.b7f506c30e65','Handicap oficial','Hándicap oficial','Official handicap'),
('text.fc182b063478','Obtén información para incorporarte a GHIN y llevar un seguimiento reconocido de tu Handicap Index.','Obtén información para incorporarte a GHIN y llevar un seguimiento reconocido de tu índice de hándicap.','Get information about joining GHIN and maintaining a recognized Handicap Index.'),
('text.2275aed69c49','Información sobre el registro.','Información sobre el registro.','Registration information.'),
('text.3c56c462fe31','Orientación para comenzar.','Orientación para comenzar.','Guidance to get started.'),
('text.0752b8ea352e','Contacto directo con Carlos.','Contacto directo con Carlos.','Direct contact with Carlos.'),
('text.c58ef72dc732','Quiero información de GHIN','Quiero información de GHIN','I want GHIN information'),
('text.6027fec34be8','Una selección local de campos. Mostramos únicamente los que estén publicados por UP AND DOWN.','Una selección local de campos. Mostramos únicamente los que estén publicados por UP AND DOWN.','A local course selection. We only show courses published by UP AND DOWN.'),
('text.0ac82759610d','Historias, guías y notas para jugar, elegir y disfrutar mejor el golf en Los Cabos.','Historias, guías y notas para jugar, elegir y disfrutar mejor el golf en Los Cabos.','Stories, guides and notes to play, choose and enjoy golf in Los Cabos.'),
('text.28963109e4cf','Ver más artículos','Ver más artículos','View more articles'),
('text.f5d0ea3438e3','Ver menos artículos','Ver menos artículos','View fewer articles'),
('text.e3f5998d5080','Golf, con criterio local.','Golf, con criterio local.','Golf, with local perspective.'),
('text.1db3ed280f2d','UP AND DOWN reúne tienda, asesoría y servicios para hacer más simple elegir, cuidar y disfrutar tu equipo de golf en Los Cabos.','UP AND DOWN reúne tienda, asesoría y servicios para hacer más simple elegir, cuidar y disfrutar tu equipo de golf en Los Cabos.','UP AND DOWN brings together shop, advice and services to make choosing, caring for and enjoying your golf equipment in Los Cabos simpler.'),
('text.7e09f91e7fce','No buscamos llenar tu bolsa por llenar. Preferimos ayudarte a encontrar lo que tiene sentido para tu juego, acompañarte cuando tu equipo necesita atención y conectarte con experiencias que suman dentro y fuera del campo.','No buscamos llenar tu bolsa por llenar. Preferimos ayudarte a encontrar lo que tiene sentido para tu juego, acompañarte cuando tu equipo necesita atención y conectarte con experiencias que suman dentro y fuera del campo.','We are not here to fill your bag for the sake of it. We prefer to help you find what makes sense for your game, support you when your equipment needs attention and connect you with experiences that add value on and off the course.'),
('text.885f9935a299','Conoce nuestros servicios','Conoce nuestros servicios','Explore our services'),
('text.4c99a4f0a81c','Quiénes somos','Quiénes somos','About us'),
('text.af5aec0ee2e7','Explorar','Explorar','Explore'),
('text.26202a1ae5fe','Cerrar búsqueda','Cerrar búsqueda','Close search'),
('text.f08daacd77bf','Elige una categoría para mostrar únicamente los filtros técnicos que correspondan.','Elige una categoría para mostrar únicamente los filtros técnicos que correspondan.','Choose a category to reveal only the technical filters that apply.'),
('text.c4e6a4c3ce49','Mostramos únicamente los filtros técnicos disponibles para esta categoría de palos.','Mostramos únicamente los filtros técnicos disponibles para esta categoría de palos.','Only technical filters available for this club category are shown.'),
('text.a700ad9bf468','Ocultamos mano, flex y loft porque no corresponden a esta categoría.','Ocultamos mano, flexibilidad y ángulo de la cara porque no corresponden a esta categoría.','Club-specific filters are hidden because they do not apply to this category.'),
('text.b67e320e0c07','Abrir carrito','Abrir carrito','Open cart'),
('text.256a5c2ab314','Abrir menú','Abrir menú','Open menu'),
('text.602bc2f77e81','Accesos rápidos a la tienda','Accesos rápidos a la tienda','Quick shop links'),
('text.538136c7d2bd','Acciones rápidas de compra','Acciones rápidas de compra','Quick purchase actions'),
('text.8aa3ec7147c1','Bolsa y equipo de golf en campo','Bolsa y equipo de golf en campo','Golf bag and equipment on the course'),
('text.9a68fd077c0c','Buscar producto, marca, modelo o shaft…','Buscar producto, marca, modelo o varilla…','Search product, brand, model or shaft…'),
('text.cf845ef822c0','Calendario de clase de entrenamiento UP AND DOWN','Calendario de clase de entrenamiento UP AND DOWN','UP AND DOWN training session calendar'),
('text.2e253641afd4','Campo de golf costero','Campo de golf costero','Coastal golf course'),
('text.e6744d320967','Campo de golf en Los Cabos','Campo de golf en Los Cabos','Golf course in Los Cabos'),
('text.e576ff0e170f','Campo de golf entre desierto y mar','Campo de golf entre desierto y mar','Golf course between desert and sea'),
('text.1daa7d99f75f','Cerrar carrito','Cerrar carrito','Close cart'),
('text.5c7643a6ba4b','Cerrar detalle','Cerrar detalle','Close details'),
('text.9f4dfc32f889','Cerrar menú','Cerrar menú','Close menu'),
('text.6ba62f0648df','Colecciones rápidas','Colecciones rápidas','Quick collections'),
('text.af436beeda3c','Compromisos de compra','Compromisos de compra','Purchase commitments'),
('text.4e339d1c0723','Galería del producto','Galería del producto','Product gallery'),
('text.f44fd8ce0e5f','Golfista preparando un golpe','Golfista preparando un golpe','Golfer preparing a shot'),
('text.7a485031179f','Green de golf','Green de golf','Golf green'),
('text.2d54e9ee7f6a','Imagen anterior','Imagen anterior','Previous image'),
('text.0d669cff38a5','Ir a tienda','Ir a tienda','Go to shop'),
('text.4854baa4e778','Marcas de golf','Marcas de golf','Golf brands'),
('text.0de570dcfe1f','Navegación móvil','Navegación móvil','Mobile navigation'),
('text.c3815f2eb4af','Navegación principal','Navegación principal','Main navigation'),
('text.db57ebcd0a93','Pelotas de golf sobre green','Pelotas de golf sobre green','Golf balls on a green'),
('text.988a4e2158c0','Siguiente imagen','Siguiente imagen','Next image'),
('text.62abd0641009','UP AND DOWN, inicio','UP AND DOWN, inicio','UP AND DOWN, home'),
('text.5c6e39b8cb6e','Visitar la página oficial de UP AND DOWN','Visitar la página oficial de UP AND DOWN','Visit the official UP AND DOWN website'),
('text.0848265b4bfc','¿Necesitas asistencia? Escríbenos por WhatsApp','¿Necesitas asistencia? Escríbenos por WhatsApp','Need assistance? Message us on WhatsApp'),
('text.77f70217bf51','Up and Down Golf Shop','UP AND DOWN · Tienda de golf','UP AND DOWN · Golf Shop'),
('text.50219b026f7f','Todo lo que necesitas para tu juego','Todo lo que necesitas para tu juego','Everything you need for your game'),
('text.5fb471f630f7','○ Seminuevos ○ Reparaciones ○ Trading ○ Clases ○ Fittings','Seminuevos · Reparaciones · Intercambios · Clases · Ajuste de equipo','Pre-owned · Repairs · Trade-ins · Lessons · Club fitting'),
('text.929d84d40045','Latest arrivals & offers','NOVEDADES Y OFERTAS','NEW ARRIVALS & OFFERS'),
('text.09ac8bcaf536','Shop by category','CATEGORÍAS','CATEGORIES'),
('text.3e91c233db88','The collection','COLECCIÓN COMPLETA','THE COLLECTION'),
('text.07d1d6195ecc','Noticias','Noticias','News'),
('text.088eb8e7de71','Múltiples servicios, atención personalizada.','Múltiples servicios, atención personalizada.','Multiple services, personalized attention.'),
('text.9500a6d5c2e2','Guías de equipo, campos de golf y noticias.','Guías de equipo, campos de golf y noticias.','Equipment guides, golf courses and news.'),
('text.30c6e31eccc7','QUIÉNES SOMOS','QUIÉNES SOMOS','ABOUT US'),
('text.507590d459ae','Campos seleccionados y publicados por UP AND DOWN para descubrir la experiencia local.','Campos seleccionados y publicados por UP AND DOWN para descubrir la experiencia local.','Courses selected and published by UP AND DOWN to explore the local golf experience.'),
('text.e8afe0fcdb5b','Una selección breve de lo nuevo y las oportunidades que vale la pena mirar.','Una selección breve de lo nuevo y las oportunidades que vale la pena mirar.','A selection of new arrivals and offers worth exploring.'),
('text.b0423c3471e7','Busca por categoría, condición y especificaciones cuando realmente apliquen.','Busca por categoría, condición y especificaciones cuando realmente apliquen.','Search by category, condition and relevant specifications.'),
('text.1dae5de955db','Revisamos desgaste, daños y fallas para explicarte alternativas antes de realizar cualquier trabajo.','Revisamos desgaste, daños y fallas para explicarte alternativas antes de realizar cualquier trabajo.','We inspect wear, damage and faults to explain your options before any work begins.'),
('text.f16bfd56b171','Cotización previa.','Cotización previa.','Quote before work begins.'),
('text.ede6fdda70c7','El alcance y precio final se confirman después de revisar físicamente el equipo.','El alcance y precio final se confirman después de revisar físicamente el equipo.','Scope and final pricing are confirmed after a physical inspection.'),
('text.d6a497db70fb','Trae tu equipo para valorar marca, modelo, condición y demanda y saber si puede aplicar como parte de pago.','Trae tu equipo para valorar marca, modelo, condición y demanda y saber si puede aplicar como parte de pago.','Bring your equipment for a brand, model, condition and demand assessment to see whether it qualifies for trade-in credit.'),
('text.9b1635a882e4','Valoración basada en condición real.','Valoración basada en condición real.','Assessment based on actual condition.'),
('text.af5cfecf2127','Posible crédito en tienda.','Posible crédito en tienda.','Potential store credit.'),
('text.1363d357941f','Aceptación sujeta a revisión.','Aceptación sujeta a revisión.','Acceptance subject to assessment.'),
('text.e8ac4c688623','Mantén tu equipo listo para la siguiente ronda con limpieza, revisión de grips y ajustes básicos.','Mantén tu equipo listo para la siguiente ronda con limpieza, revisión de empuñaduras y ajustes básicos.','Keep your equipment ready for the next round with cleaning, grip checks and basic adjustments.'),
('text.0d9af14a111c','Limpieza de cabezas y varillas.','Limpieza de cabezas y varillas.','Clubhead and shaft cleaning.'),
('text.211a1f33dc7b','Revisión de grips.','Revisión de empuñaduras.','Grip inspection.'),
('text.f67b06b0aed0','Inspección de desgaste.','Inspección de desgaste.','Wear inspection.'),
('text.813486d25754','(opcional)','(opcional)','(optional)'),
('text.1ffae0cb4a67','Golf en Cabo, bien elegido.','Golf en Cabo, bien elegido.','Golf in Cabo, thoughtfully selected.'),
('text.167c60e62d30','Somos una tienda y punto de encuentro para golfistas que prefieren elegir con criterio: equipo, servicio y conocimiento local en un solo lugar.','Somos una tienda y punto de encuentro para golfistas que prefieren elegir con criterio: equipo, servicio y conocimiento local en un solo lugar.','We are a shop and meeting point for golfers who choose thoughtfully: equipment, service and local knowledge in one place.'),
('text.de1b2060c948','No se trata de llenar la bolsa. Se trata de encontrar lo que funciona para tu juego, cuidarlo bien y disfrutar más cada ronda.','No se trata de llenar la bolsa. Se trata de encontrar lo que funciona para tu juego, cuidarlo bien y disfrutar más cada ronda.','Find what works for your game, take good care of it and enjoy every round more.'),
('text.209f5ab4bc05','Conocer servicios →','Conocer servicios →','Explore services →'),
('text.9123cc061e51','GOLF EN LOS CABOS','GOLF EN LOS CABOS','GOLF IN LOS CABOS'),
('text.004d4a7f813b','MARCAS DE GOLF','MARCAS DE GOLF','GOLF BRANDS'),
('text.1f3aac49eceb','CABO GOLF SHOP BY COQUE','TIENDA DE GOLF EN CABO · COQUE','CABO GOLF SHOP BY COQUE'),
('text.fffb0dc7bd4f','© 2026 UP AND DOWN · CABO GOLF SHOP BY COQUE.','© 2026 UP AND DOWN · TIENDA DE GOLF EN CABO · COQUE.','© 2026 UP AND DOWN · CABO GOLF SHOP BY COQUE.'),
('hero.title','UP AND DOWN · Tienda de golf','UP AND DOWN · Tienda de golf','UP AND DOWN · Golf Shop'),
('hero.subtitle','Todo lo que necesitas para tu juego','Todo lo que necesitas para tu juego','Everything you need for your game'),
('hero.services','Seminuevos · Reparaciones · Intercambios · Clases · Ajuste de equipo','Seminuevos · Reparaciones · Intercambios · Clases · Ajuste de equipo','Pre-owned · Repairs · Trade-ins · Lessons · Club fitting'),
('category.eyebrow','CATEGORÍAS','CATEGORÍAS','CATEGORIES'),
('new.eyebrow','NOVEDADES Y OFERTAS','NOVEDADES Y OFERTAS','NEW ARRIVALS & OFFERS'),
('catalog.eyebrow','COLECCIÓN COMPLETA','COLECCIÓN COMPLETA','THE COLLECTION'),
('news.title','Noticias','Noticias','News'),
('courses.all','Todos','Todos','All'),
('courses.filter','Filtrar campos por ciudad','Filtrar campos por ciudad','Filter courses by city'),
('mobile.navigation','NAVEGACIÓN','NAVEGACIÓN','NAVIGATION'),
('mobile.search','Buscar','Buscar','Search'),
('mobile.searchProducts','Buscar productos','Buscar productos','Search products'),
('mobile.searchEquipment','Buscar equipo…','Buscar equipo…','Search equipment…'),
('mobile.closeSearch','Cerrar búsqueda','Cerrar búsqueda','Close search'),
('mobile.clearSearch','Limpiar búsqueda','Limpiar búsqueda','Clear search'),
('mobile.quickSearches','Búsquedas rápidas','Búsquedas rápidas','Quick searches'),
('mobile.suggestions','Sugerencias','Sugerencias','Suggestions'),
('mobile.noMatches','Sin coincidencias todavía.','Sin coincidencias todavía.','No matches yet.'),
('mobile.closeMenu','Cerrar menú','Cerrar menú','Close menu'),
('mobile.menu','Menú','Menú','Menu'),
('mobile.cart','Carrito','Carrito','Cart'),
('mobile.shortcuts','ACCESO DIRECTO','ACCESO DIRECTO','QUICK ACCESS'),
('mobile.classes','Clases de golf','Clases de golf','Golf lessons'),
('mobile.handicap','HÁNDICAP OFICIAL','HÁNDICAP OFICIAL','OFFICIAL HANDICAP'),
('mobile.shop','Tienda','Tienda','Shop'),
('mobile.categories','Categorías','Categorías','Categories'),
('mobile.services','Servicios','Servicios','Services'),
('mobile.courses','Golf en Los Cabos','Golf en Los Cabos','Golf in Los Cabos'),
('mobile.about','Quiénes somos','Quiénes somos','About us'),
('mobile.advisor','Hablar con un asesor','Hablar con un asesor','Talk to an advisor'),
('classes.consent','Autorizo a UP AND DOWN a contactarme por WhatsApp, SMS o llamada para atender mi solicitud de clases y dar seguimiento relacionado con servicios de golf. Mi información será utilizada para gestionar esta solicitud, atención comercial y análisis interno; no será vendida a terceros. Puedo solicitar dejar de recibir mensajes en cualquier momento.','Autorizo a UP AND DOWN a contactarme por WhatsApp, SMS o llamada para atender mi solicitud de clases y dar seguimiento relacionado con servicios de golf. Mi información será utilizada para gestionar esta solicitud, atención comercial y análisis interno; no será vendida a terceros. Puedo solicitar dejar de recibir mensajes en cualquier momento.','I authorize UP AND DOWN to contact me by WhatsApp, text message or phone to handle my lesson request and related golf services. My information will be used to manage this request, customer service and internal analysis; it will not be sold to third parties. I may ask to stop receiving messages at any time.'),
('condition.demo','Demo','Demostración','Demo'),
('advisor.label','Golf Concierge','Asesor de golf','Golf advisor'),
('category.putters','Restauraciones de Putters','Restauración de palos de precisión','Putter restoration'),
('copy.search','Buscar producto, marca, modelo o shaft…','Buscar producto, marca, modelo o varilla…','Search product, brand, model or shaft…'),
('category.drivers','Drivers','Palos de salida','Drivers'),
('category.wedges','Wedges','Cuñas','Wedges'),
('category.precision','Putters','Palos de precisión','Putters')
on conflict (key) do nothing;
